name: first git 
on: 
  push: 
    branches: ['main']
jobs:
  run-app: 
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v4
      - run: sudo npm install express mongoose cors dotenv
      - run: sudo npm install pm2 -g 
      - run: sudo pm2 start server.js --name kunj  
      
